#!/usr/bin/env python3
# Simple test for NeoPixels on Raspberry Pi
import time
import board
import neopixel


# Choose an open pin connected to the Data In of the NeoPixel strip, i.e. board.D18
# NeoPixels must be connected to D10, D12, D18 or D21 to work.
pixel_pin = board.D18

# The number of NeoPixels
num_pixels = 256
step = 8

bright_step = 1.0 / (num_pixels/step)

# The order of the pixel colors - RGB or GRB. Some NeoPixels have red and green reversed!
# For RGBW NeoPixels, simply change the ORDER to RGBW or GRBW.
ORDER = neopixel.GRB

bright = bright_step
while num_pixels > 0:
	pixels = neopixel.NeoPixel(
	    pixel_pin, num_pixels, brightness=bright, auto_write=False, pixel_order=ORDER
	)

	pixels.fill((180, 0, 255))
	pixels.show()

	num_pixels -= step
	bright += bright_step
