#!/usr/bin/bash

while ! i2cdetect -l | grep chan_id.0; do
	sleep 1
done

while ! i2cdetect -y 0 0xc 0xc | grep ' 0c '; do
	sleep 1
done

f=350

value=$(( (f << 4) & 0x3ff0 ))
data1=$(( (value >> 8) & 0x3f ))
data2=$(( value & 0xf0 ))

i2cset -y 0 0x0c $data1 $data2

echo focus set to $f
